### ISSUE TITLE
[ESPHome] New Configuration Request 

### ISSUE THREAD

**Issue by JonPusey** [tube0013/TubesZB-ESPHome-Builder#11]
### Device_Name

tubeszb-cc2652p7-poe-2023

### Static_IP

192.168.87.43

### Gateway

192.168.87.1

### Subnet

255.255.255.0

**Comment by tube0013** [comment]
I'll take a look at this later today to see why the binaries weren't linked correctly. - Likely a naming inconsistency I have to fix.

**Comment by JonPusey** [comment]
I think the first one went wrong because its labelled subnet, so I entered
192.168.87.1/24 instead of 255.255.255.0
