### ISSUE TITLE
[ESPHome] New Configuration Request 2024.8.9

### ISSUE THREAD

**Issue by tube0013** [tube0013/TubesZB-ESPHome-Builder#9]
### Device_Name

tubeszb-cc2652p2-ethusb-2022

### Static_IP

192.168.178.22

### Gateway

192.168.178.1

### Subnet

255.255.255.0

**Comment by FS1961** [comment]
Thanks, so far, so good!

**Comment by FS1961** [comment]
<img width="1591" alt="Screenshot 2024-08-10 at 7 46 26 AM" src="https://github.com/user-attachments/assets/75ddf0a6-f43c-46a0-91f2-59891bef3213">

Overnight everything still good.
